# Generated by Django 4.2.3 on 2023-08-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_office_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='office',
            table='venue',
        ),
    ]
